/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NGO;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author surajvisvesh
 */
public class NGOBloodColJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOBloodColJPanel
     */
    JPanel mainFrameCardLayout;
    String ngow_username;

    public NGOBloodColJPanel(JPanel mainFrameCardLayout, String ngow_username) {
        initComponents();
        this.mainFrameCardLayout = mainFrameCardLayout;
        this.ngow_username = ngow_username;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NBCHeader = new javax.swing.JPanel();
        bloodonateLbl = new javax.swing.JLabel();
        NBCMenu = new javax.swing.JPanel();
        manageProfileBtn = new javax.swing.JPanel();
        ManageProLbl = new javax.swing.JLabel();
        proIcon = new javax.swing.JLabel();
        collectBloodBtn = new javax.swing.JPanel();
        ManageOrgLbl = new javax.swing.JLabel();
        sampleColIcon = new javax.swing.JLabel();
        transportBloodBtn = new javax.swing.JPanel();
        OrgCampsLbl = new javax.swing.JLabel();
        logisticsIcon = new javax.swing.JLabel();
        ManageDonorsPanel = new javax.swing.JPanel();
        ManageDonLbl = new javax.swing.JLabel();
        donorIcon = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CardLayoutNBCPanel = new javax.swing.JPanel();

        NBCHeader.setBackground(new java.awt.Color(223, 85, 71));

        bloodonateLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        bloodonateLbl.setForeground(new java.awt.Color(215, 215, 215));
        bloodonateLbl.setText("BLOODONATE");
        bloodonateLbl.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        javax.swing.GroupLayout NBCHeaderLayout = new javax.swing.GroupLayout(NBCHeader);
        NBCHeader.setLayout(NBCHeaderLayout);
        NBCHeaderLayout.setHorizontalGroup(
            NBCHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NBCHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bloodonateLbl)
                .addContainerGap(1168, Short.MAX_VALUE))
        );
        NBCHeaderLayout.setVerticalGroup(
            NBCHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NBCHeaderLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(bloodonateLbl)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        NBCMenu.setBackground(new java.awt.Color(223, 85, 71));
        NBCMenu.setPreferredSize(new java.awt.Dimension(220, 700));
        NBCMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageProfileBtn.setBackground(new java.awt.Color(223, 85, 71));

        ManageProLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ManageProLbl.setForeground(new java.awt.Color(215, 215, 215));
        ManageProLbl.setText("Manage Profile");

        proIcon.setBackground(new java.awt.Color(204, 204, 204));
        proIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/profile_icon.png"))); // NOI18N

        javax.swing.GroupLayout manageProfileBtnLayout = new javax.swing.GroupLayout(manageProfileBtn);
        manageProfileBtn.setLayout(manageProfileBtnLayout);
        manageProfileBtnLayout.setHorizontalGroup(
            manageProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageProfileBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(proIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ManageProLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        manageProfileBtnLayout.setVerticalGroup(
            manageProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ManageProLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageProfileBtnLayout.createSequentialGroup()
                .addComponent(proIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        NBCMenu.add(manageProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, -1));

        collectBloodBtn.setBackground(new java.awt.Color(223, 85, 71));

        ManageOrgLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ManageOrgLbl.setForeground(new java.awt.Color(215, 215, 215));
        ManageOrgLbl.setText("Sample Collection");

        sampleColIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sampleColIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/blood-bag.png"))); // NOI18N

        javax.swing.GroupLayout collectBloodBtnLayout = new javax.swing.GroupLayout(collectBloodBtn);
        collectBloodBtn.setLayout(collectBloodBtnLayout);
        collectBloodBtnLayout.setHorizontalGroup(
            collectBloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collectBloodBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sampleColIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ManageOrgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        collectBloodBtnLayout.setVerticalGroup(
            collectBloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, collectBloodBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(collectBloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageOrgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(sampleColIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NBCMenu.add(collectBloodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 280, -1));

        transportBloodBtn.setBackground(new java.awt.Color(223, 85, 71));
        transportBloodBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                transportBloodBtnMousePressed(evt);
            }
        });

        OrgCampsLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        OrgCampsLbl.setForeground(new java.awt.Color(215, 215, 215));
        OrgCampsLbl.setText("Store Sample");

        logisticsIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logisticsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/suraj/logistics_truck.png"))); // NOI18N

        javax.swing.GroupLayout transportBloodBtnLayout = new javax.swing.GroupLayout(transportBloodBtn);
        transportBloodBtn.setLayout(transportBloodBtnLayout);
        transportBloodBtnLayout.setHorizontalGroup(
            transportBloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transportBloodBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logisticsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(OrgCampsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        transportBloodBtnLayout.setVerticalGroup(
            transportBloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transportBloodBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transportBloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrgCampsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(logisticsIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NBCMenu.add(transportBloodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, -1));

        ManageDonorsPanel.setBackground(new java.awt.Color(223, 85, 71));

        ManageDonLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        ManageDonLbl.setForeground(new java.awt.Color(215, 215, 215));
        ManageDonLbl.setText("Insights");

        donorIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        donorIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/suraj/insights_icon.png"))); // NOI18N

        javax.swing.GroupLayout ManageDonorsPanelLayout = new javax.swing.GroupLayout(ManageDonorsPanel);
        ManageDonorsPanel.setLayout(ManageDonorsPanelLayout);
        ManageDonorsPanelLayout.setHorizontalGroup(
            ManageDonorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManageDonorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(donorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(ManageDonLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );
        ManageDonorsPanelLayout.setVerticalGroup(
            ManageDonorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManageDonorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ManageDonorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageDonLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(donorIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NBCMenu.add(ManageDonorsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, -1));

        jPanel9.setBackground(new java.awt.Color(223, 85, 71));
        jPanel9.setLayout(new java.awt.CardLayout());

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(215, 215, 215));
        jPanel9.add(jLabel9, "card2");
        jPanel9.add(jLabel7, "card3");

        NBCMenu.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, -1));

        CardLayoutNBCPanel.setBackground(new java.awt.Color(255, 255, 255));
        CardLayoutNBCPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NBCMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CardLayoutNBCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NBCHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NBCHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CardLayoutNBCPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NBCMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void transportBloodBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transportBloodBtnMousePressed
        // TODO add your handling code here:

        OrganizeCampsJPanel organizeCamps = new OrganizeCampsJPanel();
        CardLayoutNBCPanel.removeAll();
        CardLayoutNBCPanel.add(organizeCamps);
        ((CardLayout) CardLayoutNBCPanel.getLayout()).next(CardLayoutNBCPanel);

    }//GEN-LAST:event_transportBloodBtnMousePressed

    public void setBtnColor(JPanel panel) {

        panel.setBackground(new Color(210, 75, 60));

    }

    public void resetBtnColor(JPanel panel) {

        panel.setBackground(new Color(223, 85, 71));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardLayoutNBCPanel;
    private javax.swing.JLabel ManageDonLbl;
    private javax.swing.JPanel ManageDonorsPanel;
    private javax.swing.JLabel ManageOrgLbl;
    private javax.swing.JLabel ManageProLbl;
    private javax.swing.JPanel NBCHeader;
    private javax.swing.JPanel NBCMenu;
    private javax.swing.JLabel OrgCampsLbl;
    private javax.swing.JLabel bloodonateLbl;
    private javax.swing.JPanel collectBloodBtn;
    private javax.swing.JLabel donorIcon;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel logisticsIcon;
    private javax.swing.JPanel manageProfileBtn;
    private javax.swing.JLabel proIcon;
    private javax.swing.JLabel sampleColIcon;
    private javax.swing.JPanel transportBloodBtn;
    // End of variables declaration//GEN-END:variables
}
