/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.NGO;

/**
 *
 * @author surajvisvesh
 */
public class RequestDoctorNGOJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestDoctorJPanel
     */
    public RequestDoctorNGOJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        searchCampTF = new javax.swing.JTextField();
        serachIconLbl = new javax.swing.JLabel();
        searchHospTF = new javax.swing.JTextField();
        serachIconLbl1 = new javax.swing.JLabel();
        chooseCampLbl = new javax.swing.JLabel();
        SelectCampBtn = new javax.swing.JPanel();
        SelectCampBtnLbl = new javax.swing.JLabel();
        selectHospLbl = new javax.swing.JLabel();
        reqDocBtn = new javax.swing.JPanel();
        reqDocBtnLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 358, 1064, 173));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {"4", null, null, null},
                {"5", null, null, null},
                {"6", null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 47, 1064, 136));
        add(searchCampTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 12, 208, -1));

        serachIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/search_icon.png"))); // NOI18N
        add(serachIconLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 6, -1, -1));
        add(searchHospTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(861, 317, 208, -1));

        serachIconLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/search_icon.png"))); // NOI18N
        add(serachIconLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1075, 311, -1, -1));

        chooseCampLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        chooseCampLbl.setText("Choose a camp");
        add(chooseCampLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 12, -1, -1));

        SelectCampBtn.setBackground(new java.awt.Color(106, 106, 106));

        SelectCampBtnLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        SelectCampBtnLbl.setForeground(new java.awt.Color(255, 255, 255));
        SelectCampBtnLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SelectCampBtnLbl.setText("Select Camp");

        javax.swing.GroupLayout SelectCampBtnLayout = new javax.swing.GroupLayout(SelectCampBtn);
        SelectCampBtn.setLayout(SelectCampBtnLayout);
        SelectCampBtnLayout.setHorizontalGroup(
            SelectCampBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectCampBtnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
        );
        SelectCampBtnLayout.setVerticalGroup(
            SelectCampBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SelectCampBtnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        add(SelectCampBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(951, 197, -1, -1));

        selectHospLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        selectHospLbl.setText("Select Hospital");
        add(selectHospLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 315, -1, -1));

        reqDocBtn.setBackground(new java.awt.Color(106, 106, 106));

        reqDocBtnLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        reqDocBtnLbl.setForeground(new java.awt.Color(255, 255, 255));
        reqDocBtnLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reqDocBtnLbl.setText("Request Doctor");

        javax.swing.GroupLayout reqDocBtnLayout = new javax.swing.GroupLayout(reqDocBtn);
        reqDocBtn.setLayout(reqDocBtnLayout);
        reqDocBtnLayout.setHorizontalGroup(
            reqDocBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reqDocBtnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
        );
        reqDocBtnLayout.setVerticalGroup(
            reqDocBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reqDocBtnLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        add(reqDocBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 549, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void populateCamps() {
        
    }

    private void populateHospitals() {
        
    }
    
    private void selectCampBtnFunctionality(){
        
    }
    
    private void reqDoctorBtnFunctionality() {
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SelectCampBtn;
    private javax.swing.JLabel SelectCampBtnLbl;
    private javax.swing.JLabel chooseCampLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel reqDocBtn;
    private javax.swing.JLabel reqDocBtnLbl;
    private javax.swing.JTextField searchCampTF;
    private javax.swing.JTextField searchHospTF;
    private javax.swing.JLabel selectHospLbl;
    private javax.swing.JLabel serachIconLbl;
    private javax.swing.JLabel serachIconLbl1;
    // End of variables declaration//GEN-END:variables
}
