/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.BB;

import java.awt.CardLayout;
import model.Ecosystem.Logout;
import UI.Login.homeJPanel;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prishaa
 */
public class BB_org extends javax.swing.JPanel {

     JPanel mainFrameCardLayout;
        String username;
    /**
     * Creates new form BB_org
     */
    public BB_org(JPanel mainFrameCardLayout, String username) {
        initComponents();
        this.mainFrameCardLayout = mainFrameCardLayout;
        this.username = username;
        
        headerUserName.setText(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BBheader = new javax.swing.JPanel();
        BLOODONATE = new javax.swing.JLabel();
        headerUserName = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        BBmenu = new javax.swing.JPanel();
        manageProfileBtn = new javax.swing.JPanel();
        manageProfileIcon = new javax.swing.JLabel();
        manageProfileLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        warehouseBtn = new javax.swing.JPanel();
        warehouseLbl = new javax.swing.JLabel();
        warehouseIcon = new javax.swing.JLabel();
        sampleTestingBtn = new javax.swing.JPanel();
        SampleTestingIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sampleTestingLbl = new javax.swing.JLabel();
        BBorgCardLayout = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1440, 800));

        BBheader.setBackground(new java.awt.Color(223, 85, 71));
        BBheader.setPreferredSize(new java.awt.Dimension(1428, 80));

        BLOODONATE.setBackground(new java.awt.Color(215, 215, 215));
        BLOODONATE.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        BLOODONATE.setForeground(new java.awt.Color(215, 215, 215));
        BLOODONATE.setText("BLOODONATE");

        headerUserName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headerUserName.setForeground(new java.awt.Color(215, 215, 215));
        headerUserName.setText("jLabel1");

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/BB/logout.png"))); // NOI18N

        javax.swing.GroupLayout BBheaderLayout = new javax.swing.GroupLayout(BBheader);
        BBheader.setLayout(BBheaderLayout);
        BBheaderLayout.setHorizontalGroup(
            BBheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BBheaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BLOODONATE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 985, Short.MAX_VALUE)
                .addComponent(headerUserName)
                .addGap(55, 55, 55)
                .addComponent(logoutBtn)
                .addGap(24, 24, 24))
        );
        BBheaderLayout.setVerticalGroup(
            BBheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BBheaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BBheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BBheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(headerUserName)
                        .addComponent(logoutBtn))
                    .addComponent(BLOODONATE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        BBmenu.setBackground(new java.awt.Color(223, 85, 71));
        BBmenu.setPreferredSize(new java.awt.Dimension(280, 702));
        BBmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageProfileBtn.setBackground(new java.awt.Color(223, 85, 71));
        manageProfileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageProfileBtnMouseClicked(evt);
            }
        });

        manageProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/suraj/profile_icon.png"))); // NOI18N
        manageProfileIcon.setAutoscrolls(true);

        manageProfileLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageProfileLbl.setForeground(new java.awt.Color(215, 215, 215));
        manageProfileLbl.setText("Manage Profile");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/BB/profile_icon.png"))); // NOI18N

        javax.swing.GroupLayout manageProfileBtnLayout = new javax.swing.GroupLayout(manageProfileBtn);
        manageProfileBtn.setLayout(manageProfileBtnLayout);
        manageProfileBtnLayout.setHorizontalGroup(
            manageProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfileBtnLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(manageProfileIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageProfileLbl)
                .addGap(58, 58, 58))
        );
        manageProfileBtnLayout.setVerticalGroup(
            manageProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageProfileBtnLayout.createSequentialGroup()
                .addGroup(manageProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageProfileBtnLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(manageProfileBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(manageProfileLbl)
                            .addGroup(manageProfileBtnLayout.createSequentialGroup()
                                .addComponent(manageProfileIcon)
                                .addGap(16, 16, 16))))
                    .addGroup(manageProfileBtnLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        BBmenu.add(manageProfileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 50));

        warehouseBtn.setBackground(new java.awt.Color(223, 85, 71));
        warehouseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                warehouseBtnMouseClicked(evt);
            }
        });

        warehouseLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        warehouseLbl.setForeground(new java.awt.Color(215, 215, 215));
        warehouseLbl.setText("Warehouse");

        warehouseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/suraj/profile_icon.png"))); // NOI18N
        warehouseIcon.setAutoscrolls(true);

        javax.swing.GroupLayout warehouseBtnLayout = new javax.swing.GroupLayout(warehouseBtn);
        warehouseBtn.setLayout(warehouseBtnLayout);
        warehouseBtnLayout.setHorizontalGroup(
            warehouseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warehouseBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(warehouseIcon)
                .addContainerGap(205, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, warehouseBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(warehouseLbl)
                .addGap(52, 52, 52))
        );
        warehouseBtnLayout.setVerticalGroup(
            warehouseBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warehouseBtnLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(warehouseLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warehouseIcon)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        BBmenu.add(warehouseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        sampleTestingBtn.setBackground(new java.awt.Color(223, 85, 71));
        sampleTestingBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sampleTestingBtnMouseClicked(evt);
            }
        });

        SampleTestingIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesPackage/suraj/profile_icon.png"))); // NOI18N
        SampleTestingIcon.setAutoscrolls(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/BB/blood-bag.png"))); // NOI18N

        sampleTestingLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sampleTestingLbl.setForeground(new java.awt.Color(215, 215, 215));
        sampleTestingLbl.setText("Sample Testing");

        javax.swing.GroupLayout sampleTestingBtnLayout = new javax.swing.GroupLayout(sampleTestingBtn);
        sampleTestingBtn.setLayout(sampleTestingBtnLayout);
        sampleTestingBtnLayout.setHorizontalGroup(
            sampleTestingBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sampleTestingBtnLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(SampleTestingIcon)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sampleTestingLbl)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        sampleTestingBtnLayout.setVerticalGroup(
            sampleTestingBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sampleTestingBtnLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(SampleTestingIcon)
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(sampleTestingBtnLayout.createSequentialGroup()
                .addGroup(sampleTestingBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(sampleTestingLbl))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        BBmenu.add(sampleTestingBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 40));

        BBorgCardLayout.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BBheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BBmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BBorgCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BBheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BBmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(BBorgCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageProfileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProfileBtnMouseClicked
        // TODO add your handling code here:
        manageProfileFunctionality();
       
    }//GEN-LAST:event_manageProfileBtnMouseClicked

    private void warehouseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_warehouseBtnMouseClicked
        // TODO add your handling code here:
        warehouseFunctionality();
    }//GEN-LAST:event_warehouseBtnMouseClicked

    private void sampleTestingBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sampleTestingBtnMouseClicked
        // TODO add your handling code here:
        sampleTestingFunctionality();
    }//GEN-LAST:event_sampleTestingBtnMouseClicked

     public void setBtnColor(JPanel panel) {
        
        panel.setBackground(new Color(210, 75, 60));
        
    }

    public void resetBtnColor(JPanel panel) {
        
        panel.setBackground(new Color (223, 85, 71));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BBheader;
    private javax.swing.JPanel BBmenu;
    private javax.swing.JPanel BBorgCardLayout;
    private javax.swing.JLabel BLOODONATE;
    private javax.swing.JLabel SampleTestingIcon;
    private javax.swing.JLabel headerUserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JPanel manageProfileBtn;
    private javax.swing.JLabel manageProfileIcon;
    private javax.swing.JLabel manageProfileLbl;
    private javax.swing.JPanel sampleTestingBtn;
    private javax.swing.JLabel sampleTestingLbl;
    private javax.swing.JPanel warehouseBtn;
    private javax.swing.JLabel warehouseIcon;
    private javax.swing.JLabel warehouseLbl;
    // End of variables declaration//GEN-END:variables

    private void manageProfileFunctionality() {
        
        setBtnColor(manageProfileBtn);
        resetBtnColor(warehouseBtn);
        resetBtnColor(sampleTestingBtn);
        resetBtnColor(manageRqBtn);
        
        
         BBorgCardLayout.removeAll();
        BBorgCardLayout.add(new ManageBBProfilePage(username));
        ((CardLayout) BBorgCardLayout.getLayout()).next(BBorgCardLayout);
    }

   private void warehouseFunctionality() {
       
       resetBtnColor(manageProfileBtn);
        setBtnColor(warehouseBtn);
        resetBtnColor(sampleTestingBtn);
        resetBtnColor(manageRqBtn);
        
       BBorgCardLayout.removeAll();
        BBorgCardLayout.add(new BBWHPanel(username));
        ((CardLayout) BBorgCardLayout.getLayout()).next(BBorgCardLayout);
    }

    private void sampleTestingFunctionality() {
        resetBtnColor(manageProfileBtn);
        resetBtnColor(warehouseBtn);
        setBtnColor(sampleTestingBtn);
        resetBtnColor(manageRqBtn);
        
         BBorgCardLayout.removeAll();
        BBorgCardLayout.add(new BBSampleTestingPanel());
        ((CardLayout) BBorgCardLayout.getLayout()).next(BBorgCardLayout);
    }

    //private void manageRequestFunctionality() {
        //resetBtnColor(manageProfileBtn);
        //resetBtnColor(warehouseBtn);
        //resetBtnColor(sampleTestingBtn);
        //setBtnColor(manageRqBtn);
    //}
}
