/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Login;

import java.sql.*;
import Sql.SQLConnection;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.volunteerEnt.NGOManagement;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Ecosystem.Mail;

/**
 *
 * @author surajvisvesh
 */
public class OrgRegJPanel extends javax.swing.JPanel {

    private String imagePath = "";
    private String userCBValue;

    /**
     * Creates new form DonorRegistration
     *
     * @param userCBValue
     */
    public OrgRegJPanel(String userCBValue) {
        initComponents();
        errorVisibility();
        this.userCBValue = userCBValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        passLbl = new javax.swing.JLabel();
        stateLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        passTF = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        phoneLbl = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        streetLbl = new javax.swing.JLabel();
        streetTF = new javax.swing.JTextField();
        stateCB = new javax.swing.JComboBox<>();
        pinLbl = new javax.swing.JLabel();
        pincodeTF = new javax.swing.JTextField();
        stateError = new javax.swing.JLabel();
        licenseLbl = new javax.swing.JLabel();
        addLicBtn = new javax.swing.JPanel();
        addLicLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JPanel();
        registerLbl = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        nameError = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        passError = new javax.swing.JLabel();
        emailError = new javax.swing.JLabel();
        phoneNoError = new javax.swing.JLabel();
        streetError = new javax.swing.JLabel();
        cityError = new javax.swing.JLabel();
        usernameError = new javax.swing.JLabel();
        licError = new javax.swing.JLabel();
        pinError = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cityLbl.setText("City*");
        add(cityLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        nameLbl.setText("Organization Name*");
        add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));
        add(cityTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 305, -1));

        passLbl.setText("Password*");
        add(passLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        stateLbl.setText("State*");
        add(stateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, -1, -1));
        add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 305, -1));

        passTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTFActionPerformed(evt);
            }
        });
        add(passTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 305, -1));

        emailLbl.setText("Email*");
        add(emailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });
        add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 305, -1));

        phoneLbl.setText("Phone Number*");
        add(phoneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, -1, -1));
        add(phoneTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, 305, -1));

        streetLbl.setText("Street Address*");
        add(streetLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        streetTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetTFActionPerformed(evt);
            }
        });
        add(streetTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 305, -1));

        stateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "IllinoisIndiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "MontanaNebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "PennsylvaniaRhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming" }));
        add(stateCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 305, -1));

        pinLbl.setText("Pincode*");
        add(pinLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));
        add(pincodeTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 305, -1));

        stateError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        stateError.setForeground(new java.awt.Color(255, 51, 0));
        stateError.setText("Enter valid data");
        add(stateError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 330, -1, -1));

        licenseLbl.setText("NGO License*");
        add(licenseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, -1, -1));

        addLicBtn.setBackground(new java.awt.Color(106, 106, 106));

        addLicLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addLicLbl.setForeground(new java.awt.Color(255, 255, 255));
        addLicLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addLicLbl.setText("Add License");
        addLicLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addLicLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout addLicBtnLayout = new javax.swing.GroupLayout(addLicBtn);
        addLicBtn.setLayout(addLicBtnLayout);
        addLicBtnLayout.setHorizontalGroup(
            addLicBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addLicLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        addLicBtnLayout.setVerticalGroup(
            addLicBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addLicLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(addLicBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, -1, -1));

        registerBtn.setBackground(new java.awt.Color(106, 106, 106));

        registerLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        registerLbl.setForeground(new java.awt.Color(255, 255, 255));
        registerLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLbl.setText("REGISTER");
        registerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registerLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout registerBtnLayout = new javax.swing.GroupLayout(registerBtn);
        registerBtn.setLayout(registerBtnLayout);
        registerBtnLayout.setHorizontalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        registerBtnLayout.setVerticalGroup(
            registerBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, -1, -1));
        add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 305, -1));

        nameError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        nameError.setForeground(new java.awt.Color(255, 51, 0));
        nameError.setText("Enter valid data");
        add(nameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        usernameLbl.setText("Username*");
        add(usernameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        passError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        passError.setForeground(new java.awt.Color(255, 51, 0));
        passError.setText("Enter valid data");
        add(passError, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        emailError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        emailError.setForeground(new java.awt.Color(255, 51, 0));
        emailError.setText("Enter valid data");
        add(emailError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, -1, -1));

        phoneNoError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        phoneNoError.setForeground(new java.awt.Color(255, 51, 0));
        phoneNoError.setText("Enter valid data");
        add(phoneNoError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 140, -1, -1));

        streetError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        streetError.setForeground(new java.awt.Color(255, 51, 0));
        streetError.setText("Enter valid data");
        add(streetError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 240, -1, -1));

        cityError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        cityError.setForeground(new java.awt.Color(255, 51, 0));
        cityError.setText("Enter valid data");
        add(cityError, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        usernameError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        usernameError.setForeground(new java.awt.Color(255, 51, 0));
        usernameError.setText("Enter valid data");
        add(usernameError, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        licError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        licError.setForeground(new java.awt.Color(255, 51, 0));
        licError.setText("Enter valid data");
        add(licError, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, -1, -1));

        pinError.setFont(new java.awt.Font("Helvetica Neue", 2, 13)); // NOI18N
        pinError.setForeground(new java.awt.Color(255, 51, 0));
        pinError.setText("Enter valid data");
        add(pinError, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void passTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void streetTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetTFActionPerformed

    private void addLicLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLicLblMousePressed
        // TODO add your handling code here:
        addLicFunctionality();

    }//GEN-LAST:event_addLicLblMousePressed

    private void registerLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLblMousePressed
        try {
            // TODO add your handling code here:
            errorVisibility();
            registerBtnFunctionality();
        } catch (SQLException ex) {
            Logger.getLogger(OrgRegJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registerLblMousePressed

    public void addLicFunctionality() {

        JFileChooser imageBrowser = new JFileChooser();

        FileNameExtensionFilter fileNameFilter = new FileNameExtensionFilter("IMAGES", "jpeg", "jpg", "png");
        imageBrowser.addChoosableFileFilter(fileNameFilter);

        int showOpenDialogue = imageBrowser.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {

            File imageFile = imageBrowser.getSelectedFile();
            imagePath = imageFile.getAbsolutePath();

            JOptionPane.showMessageDialog(this, "File has been uploaded.");
            licError.setVisible(false);

        }

    }

    public void registerBtnFunctionality() throws SQLException {
        boolean valid = true;
        long phoneNo = 0;
        int pincode = 0;

        String name = nameTF.getText();
        String username = usernameTF.getText();
        String email = emailTF.getText();
        String password = passTF.getText();
        try {
            phoneNo = Long.parseLong(phoneTF.getText());
        } catch (NumberFormatException e) {
            phoneNoError.setVisible(false);
            valid = false;
        }
        String street = streetTF.getText();
        String city = cityTF.getText();
        String state = stateCB.getSelectedItem().toString();
        try {
            pincode = Integer.parseInt(pincodeTF.getText());
        } catch (Exception e) {
            pinError.setVisible(true);
            valid = false;
        }
        if (name.isEmpty()) {
            nameError.setVisible(true);
            valid = false;
        }
        if (username.isEmpty()) {
            usernameError.setVisible(true);
            valid = false;
        }
        if (email.isEmpty() || email.length() < 2 || !email.matches("^(.+)@(\\S+)$")) {
            emailError.setVisible(true);
            valid = false;
        }
        if (password.isEmpty()) {
            passError.setVisible(true);
            valid = false;
        }
        if (Long.toString(phoneNo).length() != 10) {
            System.out.println("PhoneNo");
            phoneNoError.setVisible(true);
            valid = false;
        }
        if (street.isEmpty()) {
            streetError.setVisible(true);
            valid = false;
        }
        if (city.isEmpty()) {
            cityError.setVisible(true);
            valid = false;
        }
        if (state.isEmpty()) {
            stateError.setVisible(true);
            valid = false;
        }
        if (!(Integer.toString(pincode).length() >=5 || Integer.toString(pincode).length()<= 6)) {
            pinError.setVisible(true);
            valid = false;
        }
        if (imagePath.isEmpty()) {
            licError.setVisible(true);
            valid = false;
        }
        if (valid) {
            switch (userCBValue) {
                case "NGO Organization":
                    NGOManagement ngo = new NGOManagement();
                    ngo.setName(name);
                    ngo.setUsername(username);
                    ngo.setEmail(email);
                    ngo.setPhoneNo(phoneNo);
                    ngo.setCity(city);
                    ngo.setStreet(street);
                    ngo.setPassword(password);
                    ngo.setPincode(pincode);
                    ngo.setState(state);
                    ngo.setLicense_path(imagePath);

                    try {
                        System.out.println("entered try block");
                        Connection con = SQLConnection.establishConnection();
                        System.out.println(con);
                        if (con != null) {
                            System.out.println("entered if con not null block");
                            String approval = "app";
                            String query = "INSERT INTO NGO(user_name, Name, Email, Password, Phone_number, Street_address, City, State, Pincode, license, approval_status) VALUES(?,?,?,?,?,?,?,?,?,?,?)";

                            PreparedStatement pstmt = con.prepareStatement(query);
                            pstmt.setString(1, username);
                            pstmt.setString(2, name);
                            pstmt.setString(3, email);
                            pstmt.setString(4, password);
                            pstmt.setLong(5, phoneNo);
                            pstmt.setString(6, street);
                            pstmt.setString(7, city);
                            pstmt.setString(8, state);
                            pstmt.setInt(9, pincode);

                            pstmt.setString(10, imagePath);
                            pstmt.setString(11, approval);
                            int count = pstmt.executeUpdate();
                            if (count == 1) {
                                emptyTF();

                                JOptionPane.showMessageDialog(null, "Thanks for registering. We will notify you once your registration is approved.");
//                                Mail mail = new Mail();
//                                mail.sendEmailMessage("surajvisvesh@gmail.com", "Thanks for registering with BLOODONATE. We will update you once your account is approved.");
                            }
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "User already exists. Please try a different username or email.", "Error!", JOptionPane.ERROR_MESSAGE);

                    }
            }

        }

    }

    public void errorVisibility() {

        nameError.setVisible(false);
        usernameError.setVisible(false);
        emailError.setVisible(false);
        passError.setVisible(false);
        phoneNoError.setVisible(false);
        streetError.setVisible(false);
        cityError.setVisible(false);
        stateError.setVisible(false);
        pinError.setVisible(false);
        licError.setVisible(false);

    }

    public void emptyTF() {
        nameTF.setText("");
        usernameTF.setText("");
        emailTF.setText("");
        phoneTF.setText("");
        passTF.setText("");
        streetTF.setText("");
        cityTF.setText("");
        pincodeTF.setText("");
    }

//    private static boolean isInteger(String s) {
//        try {
//            Integer.parseInt(s);
//        } catch (NumberFormatException e) {
//            return false;
//        } catch (NullPointerException e) {
//            return false;
//        }
//        return true;
//    }
//
//    private static boolean isLong(String s) {
//        try {
//            Long.parseLong(s);
//        } catch (NumberFormatException e) {
//            return false;
//        } catch (NullPointerException e) {
//            return false;
//        }
//        return true;
//    }

//    public static void sendEmailMessage(String emailId, String body) {
//        String to = emailId;
//        String from = "doneverevereply@gmail.com";
//        String pass = "Hello@123";
//
//        Properties properties = System.getProperties();
//        String host = "smtp.gmail.com";
//        properties.put("mail.smtp.starttls.enable", "true");
//        properties.put("mail.smtp.ssl.trust", host);
//        properties.put("mail.smtp.user", from);
//        properties.put("mail.smtp.port", "587");
//        properties.put("mail.smtp.auth", "true");
//
//        Session session = Session.getDefaultInstance(properties);
//        try {
//            MimeMessage message = new MimeMessage(session);
//            message.setFrom(new InternetAddress(from));
//            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
//            message.setSubject("New User Registration");
//            message.setText(body);
//            Transport transport = session.getTransport("smtp");
//            transport.connect(host, from, pass);
//            transport.sendMessage(message, message.getAllRecipients());
//            transport.close();
//            System.out.println("Sent message successfully....");
//        } catch (MessagingException mex) {
//            JOptionPane.showMessageDialog(null, "Invalid Email Address");
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addLicBtn;
    private javax.swing.JLabel addLicLbl;
    private javax.swing.JLabel cityError;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JTextField cityTF;
    private javax.swing.JLabel emailError;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel licError;
    private javax.swing.JLabel licenseLbl;
    private javax.swing.JLabel nameError;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel passError;
    private javax.swing.JLabel passLbl;
    private javax.swing.JTextField passTF;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JLabel phoneNoError;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JLabel pinError;
    private javax.swing.JLabel pinLbl;
    private javax.swing.JTextField pincodeTF;
    private javax.swing.JPanel registerBtn;
    private javax.swing.JLabel registerLbl;
    private javax.swing.JComboBox<String> stateCB;
    private javax.swing.JLabel stateError;
    private javax.swing.JLabel stateLbl;
    private javax.swing.JLabel streetError;
    private javax.swing.JLabel streetLbl;
    private javax.swing.JTextField streetTF;
    private javax.swing.JLabel usernameError;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
