/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;

/**
 *
 * @author divyagadge
 */
public class AvailableBloodListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRequestJPanel
     */
    public AvailableBloodListJPanel() {
        initComponents();
    }
    
    private void populateBloodTypeTable(){
        
    } 
    
    private void populatePatientTable(){
        
    }
    
    private void assignBloodBtnFunctionality() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        availBloodListLbl = new javax.swing.JLabel();
        patientDetailsjScrollPane = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        assignbloodBtn = new javax.swing.JPanel();
        assignbloodLbl = new javax.swing.JLabel();
        bloodInvTbl = new javax.swing.JScrollPane();
        bloodInventoryTbl = new javax.swing.JTable();

        availBloodListLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        availBloodListLbl.setText("Available Blood List");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient Id", "Name", "DOB", "Phone Number", "Blood Group", "Street Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        patientDetailsjScrollPane.setViewportView(jTable2);

        assignbloodBtn.setBackground(new java.awt.Color(106, 106, 106));

        assignbloodLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        assignbloodLbl.setForeground(new java.awt.Color(255, 255, 255));
        assignbloodLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignbloodLbl.setText("Assign Blood");

        javax.swing.GroupLayout assignbloodBtnLayout = new javax.swing.GroupLayout(assignbloodBtn);
        assignbloodBtn.setLayout(assignbloodBtnLayout);
        assignbloodBtnLayout.setHorizontalGroup(
            assignbloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(assignbloodLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );
        assignbloodBtnLayout.setVerticalGroup(
            assignbloodBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(assignbloodLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        bloodInventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Blood Bank", "Blood Group", "Units Available"
            }
        ));
        bloodInventoryTbl.getTableHeader().setReorderingAllowed(false);
        bloodInvTbl.setViewportView(bloodInventoryTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assignbloodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(bloodInvTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(patientDetailsjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(availBloodListLbl)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(511, 511, 511)
                .addComponent(assignbloodBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(availBloodListLbl)
                .addGap(62, 62, 62)
                .addComponent(bloodInvTbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(patientDetailsjScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel assignbloodBtn;
    private javax.swing.JLabel assignbloodLbl;
    private javax.swing.JLabel availBloodListLbl;
    private javax.swing.JScrollPane bloodInvTbl;
    private javax.swing.JTable bloodInventoryTbl;
    private javax.swing.JTable jTable2;
    private javax.swing.JScrollPane patientDetailsjScrollPane;
    // End of variables declaration//GEN-END:variables
}
