/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;


import java.awt.CardLayout;

/**
 *
 * @author divyagadge
 */
public class HospitalInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNWHEquipmentsJPanel
     */
    public HospitalInventoryJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageInventoryCardLayout = new javax.swing.JPanel();
        viewInventoryBtn = new javax.swing.JPanel();
        viewInventoryLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        manageInventoryCardLayout.setBackground(new java.awt.Color(255, 255, 255));
        manageInventoryCardLayout.setPreferredSize(new java.awt.Dimension(1142, 630));
        manageInventoryCardLayout.setLayout(new java.awt.CardLayout());

        viewInventoryBtn.setBackground(new java.awt.Color(106, 106, 106));

        viewInventoryLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        viewInventoryLbl.setForeground(new java.awt.Color(255, 255, 255));
        viewInventoryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewInventoryLbl.setText("View Inventory");
        viewInventoryLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewInventoryLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout viewInventoryBtnLayout = new javax.swing.GroupLayout(viewInventoryBtn);
        viewInventoryBtn.setLayout(viewInventoryBtnLayout);
        viewInventoryBtnLayout.setHorizontalGroup(
            viewInventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewInventoryLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        viewInventoryBtnLayout.setVerticalGroup(
            viewInventoryBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewInventoryLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageInventoryCardLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(viewInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewInventoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(manageInventoryCardLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewInventoryLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewInventoryLblMousePressed
        // TODO add your handling code here:
        
     
        
    }//GEN-LAST:event_viewInventoryLblMousePressed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel manageInventoryCardLayout;
    private javax.swing.JPanel viewInventoryBtn;
    private javax.swing.JLabel viewInventoryLbl;
    // End of variables declaration//GEN-END:variables
}
