/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;


import UI.Hospital.ManageHopsitalUsersJPanel;
import javax.swing.JPanel;
//import com.mysql.cj.protocol.Resultset;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.medicalEnt.ManageEquipementQuantity;



/**
 *
 * @author divyagadge
 */
public class OrderEquipmentsHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEquipmentNWHJPanel
     */
    
    ManageEquipementQuantity manageQ;
    
    public OrderEquipmentsHospitalJPanel() {
         initComponents();
        this.manageQ = new OrderEquipmentsHospitalJPanel.manageQ();
         populateHospitalUserDetailsTable();
    }
     
    
     private void populateListofBBTable() {
        int selectedRowIndex = equipmentListTbl.getSelectedRow();     //table name in the design
        DefaultTableModel model = (DefaultTableModel) equipmentListTbl.getModel();
        manageQ.populateTable(model);
    }
    
    private void populatesearchentry(){
        
    }
    
//    private void populateequipmentTable(
//    
//    }
    
//    private void quantityTable(){
//        
//    }
    
//    private void orderHEquipment(){
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchHEquipT = new javax.swing.JTextField();
        equipTable = new javax.swing.JScrollPane();
        equipmentListTbl = new javax.swing.JTable();
        orderHBtn = new javax.swing.JPanel();
        orderLbl = new javax.swing.JLabel();
        qtyHT = new javax.swing.JTextField();
        qtyHLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        equipmentListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Equipment Id", "Equipment Name", "Description", "Required Quantity", "Hospital Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        equipmentListTbl.getTableHeader().setReorderingAllowed(false);
        equipTable.setViewportView(equipmentListTbl);

        orderHBtn.setBackground(new java.awt.Color(106, 106, 106));

        orderLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        orderLbl.setForeground(new java.awt.Color(255, 255, 255));
        orderLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        orderLbl.setText("Order Equipment");
        orderLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderLblMousePressed(evt);
            }
        });

        javax.swing.GroupLayout orderHBtnLayout = new javax.swing.GroupLayout(orderHBtn);
        orderHBtn.setLayout(orderHBtnLayout);
        orderHBtnLayout.setHorizontalGroup(
            orderHBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );
        orderHBtnLayout.setVerticalGroup(
            orderHBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(orderLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        qtyHLbl.setText("Enter required Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(qtyHLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderHBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchHEquipT, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addComponent(equipTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1069, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(searchHEquipT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(equipTable, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(orderHBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtyHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyHLbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderLblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLblMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderLblMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane equipTable;
    private javax.swing.JTable equipmentListTbl;
    private javax.swing.JPanel orderHBtn;
    private javax.swing.JLabel orderLbl;
    private javax.swing.JLabel qtyHLbl;
    private javax.swing.JTextField qtyHT;
    private javax.swing.JTextField searchHEquipT;
    // End of variables declaration//GEN-END:variables

    

    private void populateHospitalUserDetailsTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private static class manageQ extends ManageEquipementQuantity {

        public manageQ() {
        }
    }
}
