/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Hospital;

/**
 *
 * @author divyagadge
 */
public class ViewInventoryHospitalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListofBBJPanel
     */
    public ViewInventoryHospitalJPanel() {
        initComponents();
    }
    
    private void populateTable(){
        
    } 
     
    
    private void donorListBtnFunctionality() {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EquipmentHopsitaljTable = new javax.swing.JTable();
        ordEquipmentBtn = new javax.swing.JPanel();
        ordEquipmentLbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1142, 702));

        EquipmentHopsitaljTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Equipment Id", "Equipment Name", "Description", "Available Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(EquipmentHopsitaljTable);

        ordEquipmentBtn.setBackground(new java.awt.Color(106, 106, 106));

        ordEquipmentLbl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        ordEquipmentLbl.setForeground(new java.awt.Color(255, 255, 255));
        ordEquipmentLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ordEquipmentLbl.setText("Order New Equipment");

        javax.swing.GroupLayout ordEquipmentBtnLayout = new javax.swing.GroupLayout(ordEquipmentBtn);
        ordEquipmentBtn.setLayout(ordEquipmentBtnLayout);
        ordEquipmentBtnLayout.setHorizontalGroup(
            ordEquipmentBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordEquipmentLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );
        ordEquipmentBtnLayout.setVerticalGroup(
            ordEquipmentBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ordEquipmentLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(813, 813, 813)
                        .addComponent(ordEquipmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(ordEquipmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EquipmentHopsitaljTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel ordEquipmentBtn;
    private javax.swing.JLabel ordEquipmentLbl;
    // End of variables declaration//GEN-END:variables
}
